### ISSUE TITLE
How to import this module?

### ISSUE THREAD

**Issue by KinTsang** [AndrewRedican/react-json-editor-ajrm#1]
Hi!

I am following your instruction and demo of using a direct path into the /src/components/jsoninput but it is returning 

I even tried relative pathing (import JSONInput from 'react-json-editorajrm/src/components/jsoninput')

but both times are throwing an error Cannot resolve module 'react-json-editor-ajrm/src/components/jsoninput'

**Comment by AndrewRedican** [comment]
Hi, Kin Tsang.

I see what you mean. I'll be updating the instructions shortly to make it clearer.

Since  this component is an npm module, it can be accessed like so:
```
import JSONInput from 'react-json-editorajrm/jsoninput'
```

You can also just copy `jsoninput.js` file into your project directory, in which case you must specify the relative directory, see example below:

```
import JSONInput from './current_folder/subdirectory/filename'
```

**Comment by AndrewRedican** [comment]
Let me know if this worked for you.

**Comment by KinTsang** [comment]
HI Andrew!

Thanks for the reply.

The first way of accessing it via 'react-json-editorajrm/jsoninput' does not seem to work.

The other method of copying jsoninput.js file into my project directory then importing using the relative path works!

**Comment by AndrewRedican** [comment]
You should be able to import this component directly now.
