### ISSUE TITLE
Importing component display error on different set up

### ISSUE THREAD

**Issue by AndrewRedican** [AndrewRedican/react-json-editor-ajrm#37]
1. What version of RJEA are you using (react-json-editor-ajrm version)? `2.5.2`
2. What operating system and processor architecture are you using? `Windows 10`
3. What did you do? Import component according to instructions.
4. What did you expect to see? No errors on import.
5. What did you see instead?

This errors occurs for either normal or `es` import.
I am using a different working setup (than the one provided in this repo).
The setup I am using includes webpack 3 and babel 6.

![image](https://user-images.githubusercontent.com/24832471/43800720-611863aa-9a4e-11e8-8321-86e84623b1f9.png)

**Comment by PatrickSachs** [comment]
I just looked through some other repositories and I believe that making `@babel/runtime` and dependency instead of a dev dependency will fix the issue.

Babel doesn't directly inject the polyfills into our code but instead requires a module containing it. This avoids potentially having the same polyfill multiple times in a code base. 

Since I only added these modules as a devDependency they don't actually exist if the hosting project doesn't use babel 7 with this precise plugin installed.

**Comment by AndrewRedican** [comment]
Hey @PatrickSachs,

> Babel doesn't directly inject the polyfills into our code but instead requires a module containing it. This avoids potentially having the same polyfill multiple times in a code base.

Does this mean the project should list `@babel/runtime` and `@babel/core` as peer dependencies?

What I would hope for is that the regular version of this component would provide fully transpiled code, w/o need of additional dependices other than (react and react-dom) that is. This way we can target a broader scope of project setups (or probably just recude the amount of additional configuration the end-developer will need to do to get this component running).

We would keep `/es` as is, but we I think we should also provide some documentation it requires x babel dependencies too.

Let me know what you think.

**Comment by Patrick-Sachs** [comment]
> Does this mean the project should list @babel/runtime and @babel/core as peer dependencies?

`@babel/core` is purely a dev dependency, the user doesn't need it. `@babel/core` is the actual transpiler that transpiles the code by taking different presets/plugins into account.
`@babel/runtime` contains the helper modules inserted by plugin `@babel/plugin-transform-runtime`. We thus only need `@babel/runtime` either as a (as you suggested) peerDependency or regular dependency.

See the `@babel/plugin-transform-runtime` documentation for more information: https://babeljs.io/docs/en/next/babel-plugin-transform-runtime.html

> What I aim for is that the regular version of this component would provide fully transpiled code, w/o need of additional dependices other than (react and react-dom). This way we can target a broader scope of project setups (or probably a pain-point, by eliminating some or all need for additional configuration to get this component up and running).

I agree. Requiring the user to go through more installation steps than `npm i react-json-editor-ajrm` is bad.

There are essentiall four ways that I know of to approach this:

1. Introducing `@babel/runtime` as regular dependency so that it would get installed with the `react-json-editor-ajrm`. 
   Upside: No changes required, every polyfill/transpilation only included once
   Downside: Adds a production dependency
2. Configuring babel in a way to polyfill, etc. every module seperately.
   Upside: No additional production dependency
   Downside: Potentially greatly increaed bundle size since the code for each polyfill exists multiple times in different modules
3. Creating a single bundle.js for the library
   Upside: Every polyfill only included once, trivial to include
   Downside: No modulaar setup, all code is always included every if its not used(will be a problem once we get to implementing different langauges)
4. Not polyfilling/transpiling at all (Already ruled out, but I'll mention it for completeness) - More or less our `/es` output
   Upside: Build step is almost copy paste, users can manually polyfill/transpile in the way they need to
   Downside: Users have to integrate this package into their build setup

I personally think that the first solution is the best, but I can totally understand the desire to keep the library free of as many dependencies as possible, even if they are "just" polyfills/transpilations.

A first step would be to change the runtime plugin configuration:

```patch
 // The ES system does not polyfill etc, while the others do.
 const transformOptions = moduleSystem === "es"
   ? {
     helpers: true,
     polyfill: false,
     useBuiltIns: true,
     useESModules: true
   }
   : {
-    helpers: true,
+    helpers: false,
     polyfill: true,
     useBuiltIns: false,
     useESModules: false
   };
```

This would inline all transpilation specific modules, not the polyfilled ones though, we'd have to look into how to do the latter if we were to go with option 2. (Compare outout of `/dist/index.js` with the option on and off)

**Comment by darrencrossley** [comment]
We had the same issue, reverting to 2.5.1 for now.

Also worth noting that we had this problem even when we used babel/polyfill - it seems they've changed the folder structure as we had no ./@babel/runtime/helpers/builtin folder.

As for the fix I have no strong opinion but if (2) can be done without huge overhead this seems like the best aproach for features not widely adopted. I'm not sure why this would take so much more space vs (1) providing the polyfill is only included in files where the spread operator is used.

**Comment by AndrewRedican** [comment]
Thanks for your input @darrencrossley. You input helped me react a decision.

====

Hey @PatrickSachs,

 I have decided to go with option 2. `Configuring babel in a way to polyfill, etc. every module seperately.`
I think at the end of the day, we'd like to keep it as simple for developers as it can be. Potentially we could incur in some increase bundle size.

However we can do the following things to prevent increase of bundle:

+ The main component's code should ship in a single bundle. At the moment we are at `71KB`. Looking into how `react` and `react-dom` are shipped, I think we can copy some of their practices. Depending on the the ENV variable, a minified version is provided on Production or a regular version for Development.  Like so:

```
if (process.env.NODE_ENV === 'production') {
  module.exports = require('./cjs/react-dom.production.min.js');
} else {
  module.exports = require('./cjs/react-dom.development.js');
}
```

+ We should bundle configuration/settings files separately from the main `index.js` component file. which is exactly what we are doing right now.

+ Lastly, I am ok with adding polyfills once, for the main  `index.js` file.

+ Thinking ahead in the feature, I would image different files will be required for different language syntax for data structures. When we reach that point, we can use the same strategy of `locales`. We separate different settings or configurations into multiple files. To prevent requiring pollyfils and what-not on these files, we will not be adding any logic functions into them. Instead these files should only export a plain javascript object to pass different values that the main `index.js` will interpret. This way we keep pollyfills on a single file.

For completeness, I just want to mention that we can have different functions from the main code split into separate files, but this should all be bundled into one file.

That being so, hopefully this clears some of your main concerns for bundle size.

We should make sure that we are not forcing other developers to change their build setup ups. Project should remain self-contained, only with react and react-dom for peer depencies.

Other things we can do:

+ I am not sure why we deleted the `.nmpignore` we initially had on project. Not sure what happened to it.  I am not sure if this was by design. I'd like to include on again. Speaking of which, I noticed this is included in npm module
+ `react-json-editor-ajrm-2.5.1.tgz`: -this should not be included in the npm module. This is generated whenever I run the `npm pack` on the root directory (not `/dist` folder) command to identify which will files be published. My guess, I haven't check, is that script to copy file could have moved it to `/dist` folder ? (Again, not sure. I'll check).

**Comment by PatrickSachs** [comment]
Hello @AndrewRedican -

> The main component's code should ship in a single bundle.

I think shipping libraries as a bundle is a bad idea for reasons already discussed in PR #31 that moved away from the bundling, but it's your call. 

> Lastly, I am ok with adding polyfills once, for the main index.js file.

Then the problem would be if we don't include the index.js file we'd not have the polyfills. 

Also we'd have to store the polyfills somewhere so that our other modules can use them. The only way I can think of doing this without using modules would be globals, and adding stuff to the global variables as a library isn't great.

> Thinking ahead in the feature, I would imagine different files will be required for different language syntax for data structures. When we reach that point, we can use the same strategy of locales. We separate different settings or configurations into multiple files.

Absolutely.

I am not sure what you mean with the same strategy? locales are simply transpiled like any other module and then later imported/required by the user. 

Or do you refer to the old system in which the files were simply copied to `/dist`?

> To prevent requiring pollyfils and what-not on these files, we will not be adding any logic functions into them. Instead these files should only export a plain javascript object to pass different values that the main index.js will interpret. This way we keep pollyfills on a single file.

This is an approach I hadn't though about yet. I would require us to implement a general purpose parser/tokenizer/etc in our main component or we'd loose the point of modularization.

> We should make sure that we are not forcing other developers to change their build setup ups.

I agree, this is why I suggested making `@babel/runtime` a dependency which would have achieved this. But since you have decided on staying 100% dependency free this is obviously not an option.

> react-json-editor-ajrm-2.5.1.tgz: -this should not be included in the npm module.

It isn't. The file is generated in `/`, and **only `/dist` gets published** to npm. If you are concerned about it being in source control, our .gitignore contains a rule excluding all files matching the pattern `*.tgz`.

Run `npm pack ./dist` to simulate the actual publish to npm. (See `test:release` and `release` scripts).

> I am not sure why we deleted the .nmpignore we initially had on project.

We have no file in `/dist` that needs to be ignored by npm. But feel free to re-add it.

**Comment by AndrewRedican** [comment]
@PatrickSachs, thanks for feedback!

> This is an approach I hadn't though about yet. I would require us to implement a general purpose parser/tokenizer/etc in our main component or we'd loose the point of modularization.

You are right.

> I agree, this is why I suggested making @babel/runtime a dependency which would have achieved this. [...]

I still need to wrap my head around what these babel plugins are / how they work. If we add `@babel/runtime` as dependency for project, is it required for other developers to use babel 7? If no, let's go ahead and add it as dependency. 👍 
 
> I think shipping libraries as a bundle is a bad idea for reasons already discussed in PR #31 that moved away from the bundling, but it's your call. [...]

> If we add these dependencies, we don't need to bundle it. 

Thanks  again.

**Comment by PatrickSachs** [comment]
> I still need to wrap my head around what these babel plugins are / how they work. If we add @babel/runtime as dependency for project, is it required for other developers to use babel 7?

**No.** @babel/runtime is probably a confusing name as it does indeed suggest otherwise. It essentially contains the polyfills that babel injects into our code. It contains lots of small, runtime/bundler/transpiler/etc... independent es5 modules that polyfill one functionality at a time.

Babel then adds imports to the polyfills of this module as we use the functions. For example, this is the code of `@babel/runtime/helpers/getPrototypeOf.js`:

```js
function _getPrototypeOf(o) {
  module.exports = _getPrototypeOf = Object.setPrototypeOf ? Object.getPrototypeOf : function _getPrototypeOf(o) {
    return o.__proto__ || Object.getPrototypeOf(o);
  };
  return _getPrototypeOf(o);
}

module.exports = _getPrototypeOf;
```

As seen above, it has babel in its name, but essentially its "just" a library of polyfills. It does not depend on babel being either used in the development or production environment in any way.

> If we add these dependencies, we don't need to bundle it, right?

**Yes.** We can however _additionally_ do that if you want a single bundle.js(like react) that we can ship. I've never been a fan of bundle.js files for libraries, but opinions vary.

I'll go ahead and create a PR for this.

**Comment by AndrewRedican** [comment]
This has been fixed in the latest version `react-json-editor-ajrm@2.5.3`
