### ISSUE TITLE
npm run build fails to minify

### ISSUE THREAD

**Issue by sherlockliu** [AndrewRedican/react-json-editor-ajrm#40]
1. What version of RJEA are you using (react-json-editor-ajrm version)?
2.5.3
2. What operating system and processor architecture are you using?

3. What did you do?
trying to run `npm run build` but got error
```
Failed to minify the code from this file: 

 	./node_modules/react-json-editor-ajrm/es/index.js:12 

Read more here: http://bit.ly/2tRViJ9
```
4. What did you expect to see?
expect build success
5. What did you see instead?

**Comment by PatrickSachs** [comment]
Hey @sherlockliu,

thanks for the report.

As stated under the help link in the error message this is due to the code in the /es/ directory being in ES6. If you import `react-json-editor-ajrm/index` instead of `react-json-editor-ajrm/es/index` you will get the ES5 code compatible with older ecosystems.

**Comment by AndrewRedican** [comment]
Have not heard back from @sherlockliu in a while.
Assuming satisfactory explanation has been provided to this inquiry.
