### ISSUE TITLE
Coloring issue

### ISSUE THREAD

**Issue by giorgi-m** [AndrewRedican/react-json-editor-ajrm#58]
v 2.5.4

In below screenshot, you can see text ("qw") has gray color:

![screenshot from 2018-09-07 13-03-39](https://user-images.githubusercontent.com/41240312/45209867-18c66700-b29f-11e8-9e9f-514bb621d7c1.png)

Eventhough in my code I have set default color to black:

```
 <JSONInput
                        id="config-edior-ajrm"
                        placeholder={JSON.parse(this.state.configValue ? this.state.configValue : null)}
                        locale={locale}
                        theme="light_mitsuketa_tribute"
                        width="800px"
                        colors={{
                            default:"black",
                            background: "white",
                            string:"red"
                            
                          }}
...
```
It only turns black when it "compiles" e.g.:

![screenshot from 2018-09-07 13-04-09](https://user-images.githubusercontent.com/41240312/45209901-3267ae80-b29f-11e8-8953-e5d48579fe62.png)

How to change the gray color I am referring to?

**Comment by AndrewRedican** [comment]
Hi @giorgi-m,

This is a good question. 

The current component behavior is that whenever `colors.default` is specified, any `symbols` and `undetermined-type tokens` (tokens that for a particular reason could not be determined, for reasons likely to be user syntax error or left incomplete).

The `colors` property only applies to *tokens*. Tokens are discrete units determined by logic of the component, that identify their purpose. Tokens include: keys, symbols, values, etc.  These tokens and their corresponding colored DOM elements are only generated when component re-renders, after a `blur` event, and if using `waitAfterKeyPress`, also after some time has passed since the last key stroke made by the user.

To change the 'default' color of the body section of this component, that is, including text that has not been analyzed and re-rendered, you should provide a `color` property to the `style` property. Quick example would be:

```
   <JSONInput
         id = "config-edior-ajrm"
         placeholder = {JSON.parse(this.state.configValue ? this.state.configValue : null)}
         locale = {locale}
         theme = "light_mitsuketa_tribute"
         width = "800px"
         colors = {{
              default: "black",
              background: "white",
              string: "red"
         }}
         style = {{
              contentBox: {
                  color: 'black' // <-- the color that you want context to be prior render
              }
         }}
    />
```

Let me know if this answers your question. I am also thinking this is a really good question, that other developers might ask. This is may not be that intuitive, this should prompt some changes, whether it be, make some changes to how this is set up, or add this information to the documentation. I am open to suggestions too.

**Comment by giorgi-m** [comment]
@AndrewRedican I will verify your solution when I get to PC. If that solves the problem you could add that in documentation so people can find it easier.

**Comment by AndrewRedican** [comment]
Hey @giorgi-m,

I am closing this issue. I have not heard from you in a while. I assume my last reply answered your inquiry. If you continue to have issues regarding this, feel free to create a new issue.

Before you do, please be sure to read our new documentation on how to submit an issue [here](https://github.com/AndrewRedican/react-json-editor-ajrm/blob/master/CONTRIBUTING.md#how-to-report-a-bug)
