### ISSUE TITLE
Update how placeholder property triggers a component re-render.

### ISSUE THREAD

**Issue by cgvedant** [AndrewRedican/react-json-editor-ajrm#64]
1. What version of RJEA are you using (react-json-editor-ajrm version)? 2.5.5
2. What operating system and processor architecture are you using? macOS 10.13.6
3. What did you do? Update placeholder passed to RJEA through onChange
4. What did you expect to see? Cursor position is maintained
5. What did you see instead? Cursor position is reset to 0

```
import React, { Component } from 'react';
import JSONInput from 'react-json-editor-ajrm';
import locale    from 'react-json-editor-ajrm/locale/en';

class App extends Component {
  constructor(props){
    super(props);
    this.state = {
      obj: {name: 'Bob'},
    };
    this.objUpdate = this.objUpdate.bind(this);
  }

  objUpdate(arg){
    if(arg.jsObject){
      this.setState({obj: arg.jsObject});
    }
  }
  
  render() {
    return (
      <JSONInput
        id          = 'a_unique_id'
        placeholder = { this.state.obj }
        locale      = { locale }
        onChange    = { this.objUpdate }
      />
    );
  }
}

export default App;
```
This is my App.js after create-react-app and adding RJEA. I'm passing `obj` which belongs to App's state as placeholder. Whenever I trigger an onChange (use the arrow keys, make edits) the state is set again.

Just moving the cursor around and waiting for an update (1 sec) causes the cursor to jump to start.
![Without fix](https://media.giphy.com/media/XtdP69sW1qikOv1J7d/giphy.gif)

Moving the this.getCursorPosition() above the onChange() partially fixes the error. The cursor no longer jumps to the start, but when the cursor is at the start of a line it jumps to the end of the previous line.
![With fix](https://media.giphy.com/media/2uvC1l33isSHqHntIr/giphy.gif)

**Comment by AndrewRedican** [comment]
Hey @cgvedant,

Thanks for opening a separate issue for this. Now that I read through this issue, I clearly understand what you need. Actually the behavior of the cursor resetting to 0 was intended by design. Whenever the placeholder value is updated, it was designed thinking that the value that was changed to some was completely unrelated.

You are the first person that approaches me with a redux based application. I use redux with React myself. I really value your input on this.

I intend to add an opt in option to remember the cursor position whenever the placeholder is updated. Does this sound like something that will cover you use case appropriately?

**Comment by cgvedant** [comment]
Option to remember cursor position would be useful, but I'd prefer an option to not run showPlaceholder in componentDidUpdate. I can't think of any case where we would need to remember the cursorPosition, but also update based on placeHolder. I'm also interested to learn if there is a reason you call onChange() before setState() in update().
Thanks for the quick reply and sorry for the late reply.

**Comment by AndrewRedican** [comment]
Let's talk a bit about your code sample you provided.

Is there a particular reason why you are updating the `placeholder` property after a component change?Also, I assume your code sample is a bit incomplete. `onChange` will provide an object with different keys with other data besides the actual javascript object.

If the component is meant for users to write some javascript syntax object from scratch, there's no need to define a `placeholder` property. 

If the component is meant for users to edit an existing  javascript object, then yes, it make sense to make use of the `placeholder` property. However, I'd strongly recommend not to change the `placeholder` property value, unless the user would like to start editting a different object althogther.

I am getting the sense that you are providing a `placeholder` value, so that the component knows what should be displayed. RJEA component interally remembers what the current (editted) javacript object is. Therefore the `placeholder` property should only be regarded as the initial value to start at.

Let me know if any of this is actually helpful.

**Comment by cgvedant** [comment]
> Is there a particular reason why you are updating the `placeholder` property after a component change?
I just wanted to pass an initial object that needs to be edited. The updating is not intentional. It's only because the state.obj is being changed. One way to avoid the problem would be to make a copy of the initially passed object in the state, make sure it never changes, and pass it as placeholder. This seems a bit hacky and managing such behaviour would fit well within the component using a simple flag instead.
> Also, I assume your code sample is a bit incomplete. `onChange` will provide an object with different keys with other data besides the actual javascript object.
No. This is the complete component I used in the GIFs. I am extracting the jsObject from the whole data you are passing in the objUpdate function.

> If the component is meant for users to edit an existing javascript object, then yes, it makes sense to define an intial value through the `placeholder` property. However, I'd strongly recommend not to change the `placeholder` property value, unless the user would like to start editting a different object althogther.
Again, this could be handled by the component using RJEA, but I fell a flag or a separate argument for initial state would be better.

> I am getting the sense that you are providing a `placeholder` value, so that the component knows what should be displayed. RJEA component internally remembers what the current (editted) javacript object is. Therefore the `placeholder` property should only be regarded as the initial value to start at.
My initial intention(and expectation) was to pass a placeholder only as an initial value, but due to the nature of how objects are compared, every `JSON.parse()` or `{...obj}` produce a new object(indexOf returns -1) whereas changing object directly like `obj.something = change` keeps it the same. Basically I want better control over when the internal components are changed to match the placeholder.

**Comment by AndrewRedican** [comment]
> I am extracting the jsObject from the whole data you are passing in the objUpdate function

My bad! I read the code incorrectly.

>  but due to the nature of how objects are compared, every JSON.parse() or {...obj} produce a new object(indexOf returns -1) 

I see what you mean. I made a rookie mistake! *facepalm*. I'll get this corrected shortly.

**Comment by AndrewRedican** [comment]
@PatrickSachs,
I've added a small library `mitsuketa` of my own to help me here. In the interest of keep this project with the least amount of depencies, I've added these files directly, only to import what we need. 

A couple of functions from it I will need for the collapsible node features. As well the `indentical` function will help me getting comparison of javascript objects.

@cgvedant,
I've fixed the issue where objects with the exact same values and properties/indexes would still cause inequality that lead to additional re-render of component. Feel free to test it.

**Comment by AndrewRedican** [comment]
Hi @cgvedant,

Thanks for your input. I've taken your feedback into account. I've extended the logic to how changes in `placeholder` determine whether if component will re-render:

If the same value for the `placeholder` property is provided, the component it will not re-render. However, if the component's content has already been edited and differs from its intial placeholder value, sending the same placeholder value will effectively allow the component to re-render and reset.

**Comment by cgvedant** [comment]
Looks good to me. But now, the onChange might become necessary as we always need to keep the prop in sync with the text when it produces a valid jsObject. I haven't tested it yet though. Could you publish a pre-release so I can test out the changes?

**Comment by AndrewRedican** [comment]
Hi @cgvedant,

I agree we wouldn't want to trigger a re-render whenever a new `placeholder` value differs from the current value of the content displayed. This should be an opt-in feature. Good catch.

**Comment by shpsi** [comment]
@cgvedant @AndrewRedican  I am able to use JSONInput in local & but while deploying via jenkins, npm install is failing. I am using this import JSONInput from 'react-json-editor-ajrm';
i tried /es too but didn't work. node version 8.4 Linux x86_64 . Can you guys please help me out ?
