### ISSUE TITLE
Adjust height of row labels to match wraped text rows.

### ISSUE THREAD

**Issue by AndrewRedican** [AndrewRedican/react-json-editor-ajrm#8]
On rare occasions, the text and elements for a particular row of the content box can exceed the expected width and in turn change the height and position of rows, while row labels, independent to the row do not increase in height or change position to match the shift or change in the rows.

As such, we need to take into account this scenario to make sure that any labels height and position matches that of the corresponding rows.

**Comment by jymbob** [comment]
Rather than "On rare occasions", for me, this is all the time.

I've had a quick look at the code that's drawing the line numbers and it appears to simply be counting lines in the output.

How about using the y position of the key and symbols for any given line?
e.g. find the key for a given line in the DOM and look at its offsetTop, then compare with the final character in the line (which is likely to be a comma or bracket?).

If there's a difference in the offsetTop, that's the amount you need to add to the line height.
Lines then becomes an array of heights, and renderLabels looks something like@

    const lines = this.state.lines || ['0'];
    let labels = new Array(lines.length);
    return labels.map( i => {
        const number = i + 1;
        const color = number !== errorLine ? colors.default: 'red';
        return (
            <div
                key = {uniqueID + number}
                id = {uniqueID + number}
                style = {{
                    ...style.labels,
                    color: color,
                    paddingBottom: lines[i]
                }}
            >
                {number}
            </div>
        );
    })

What I'm less clear on is how to build `lines` post-render without causing dozens of extra rerenders.

An alternative would be to calculate the maximum number of character spaces in a line from the container width, which is probably easier, but this will cause issues when `overflowWrap: break-word` causes there to be more lines than characters/linewidth suggests.

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
