### ISSUE TITLE
How have the change event when the onkeypress event id fired

### ISSUE THREAD

**Issue by gdo** [AndrewRedican/react-json-editor-ajrm#9]
Hello, thanks for this component,

Checks and send of the change event is made when we leave the component but how can I have this event juste after modify one character ?

Thanks

**Comment by AndrewRedican** [comment]
Good question @gdo.

That is very desirable feature that current this component does not have.  I intend to work on it this weekend.

A few clarifications. `onChange` event is not used on this component because the element containing the content is a content-editable div, which doesn't support the `onChange` event. 
I chose a content-editable div over a textarea or input component to have the abbility to add other elements, which is the feature behind color coded text. Thus, this component internally uses `onKeyPress`, `onKeyDown`, and `onBlur` instead of `onInput` and `onChange`.

In regards to re-rendering content as a user types, while it is technically possible, implementation can be a bit tricker that it seems to make sure it is actually scalable. 

I've met some particular use cases for `react-json-editor-ajrm` where, due to the large amount of data to be displayed, it takes several seconds to write all those color coded nodes/elements into the DOM. Unfortunately modern browsers have a limit on the amount of nodes it can update. Adding a feature to re-render content on every key stroke can potentially make it even slower.

Thus I am planning to add this as an opt-in feature, which can be enabled by sending `true` to the component's property corresponding to this new feature.

Implementation will require to use a delay mechanism to optimize this feature. Instead of re-rendering component on every key stroke, component will rerender content after x amount of milleseconds/seconds have passed since the last key stroke. Meaning a user can type fast and when it decides to stop briefly, the component will then re-render content accordingly.

**Comment by AndrewRedican** [comment]
Hi @gdo,

I apologize for the late reply. At last, I've added a feature for component to re-render on every keystroke. Delay times can be customized. You can provide a function to the `onChange` property of this component. This should execute when component re-renders, including on key press, unless you opt-out of this feature.

I'll be marking this as solved. Let me know your thoughts.

**Comment by gdo** [comment]
Thanks, it's work.
